# Generated by Django 5.2.5 on 2025-12-04 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0003_movie_media_type'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='movie',
            name='playlist_movie_unique_tmdb_media_type',
        ),
        migrations.AddField(
            model_name='playlistitem',
            name='user_rating',
            field=models.PositiveSmallIntegerField(blank=True, help_text='User rating from 1-5 stars', null=True),
        ),
        migrations.AddConstraint(
            model_name='movie',
            constraint=models.UniqueConstraint(condition=models.Q(('tmdb_id__isnull', True), _negated=True), fields=('tmdb_id', 'media_type'), name='playlist_movie_unique_tmdb_media_type'),
        ),
    ]
