# Generated by Django 5.2.5 on 2025-12-05 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0006_cleanup_orphaned_playlists_and_make_user_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='is_status_playlist',
            field=models.BooleanField(default=False, help_text='True for automatic Watched/Watching/To Watch playlists'),
        ),
    ]
