# Generated by Django 5.2.5 on 2025-12-07 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0011_episodeprogress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episodeprogress',
            name='status',
            field=models.CharField(choices=[('watching', 'Watching'), ('completed', 'Completed')], default='watching', max_length=32),
        ),
    ]
