# Generated by Django 5.2.5 on 2025-12-07 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0011_remove_episodeprogress_unique_constraint'),
        ('playlist', '0012_alter_episodeprogress_status'),
    ]

    operations = [
    ]
