# Generated by Django 5.2.5 on 2025-12-08 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0014_remove_episodeprogress_unique_sql'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episodeprogress',
            name='status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='not_started', max_length=32),
        ),
    ]
